# -*- coding: utf-8 -*-
"""Projeto_mentoria_DS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iS_Es8WDncHxjpicQaJoLoSDCiyilm1O
"""

import pandas as pd
import seaborn as sns
import plotly.express as px
from sklearn.preprocessing import OneHotEncoder

df = pd.read_csv('cat_acidentes.csv',sep=';')

df['houve_mortes'] = df['mortes'] + df['morte_post']

df['houve_feridos'] = df['feridos'] + df['feridos_gr']

df['carros'] = df['auto'] + df['taxi']

df['onibus'] = df['onibus_met'] + df['onibus_urb'] + df['onibus_int']

columns = ['data', 'houve_feridos',  'houve_mortes', 'carros', 'onibus', 'caminhao', 'moto', 'dia_sem', 'noite_dia', 'regiao']
dfcopy = df[columns].copy()

dfcopy.head()

dfcopy["noite_dia"] = dfcopy["noite_dia"].apply( lambda x: int(bool(x == 'DIA'))) #em homenagem ao Gandara: transforma dia e noite em binário

dfcopy['dia_da_semana'] = dfcopy['dia_sem'].apply(lambda x: int(bool((x == 'SÁBADO') or (x == 'DOMINGO')))) #transforma em 1 se for final de semana

dfcopy.head()

dfcopy.drop('dia_sem', axis=1, inplace=True) #inplace = true aplica a alteração na tabela

dfcopy.drop('regiao', axis=1, inplace=True)

grupo1 = dfcopy.groupby('dia_da_semana').mean()

grupo1

sns.pairplot(dfcopy)

grupo2 = dfcopy.groupby('noite_dia').mean()

grupo2

fig = px.area(dfcopy, x='moto', y='houve_mortes')
fig.show()

dfcopy.head()